/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_a5_encryption_TestTools */

#ifndef _Included_com_thinking_a5_encryption_TestTools
#define _Included_com_thinking_a5_encryption_TestTools
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_thinking_a5_encryption_TestTools
	 * Method:    do_test
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_com_thinking_a5_1encryption_TestTools_do_1test
		(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
