/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_a5_encryption_EncrypTools */

#ifndef _Included_com_thinking_a5_encryption_EncrypTools
#define _Included_com_thinking_a5_encryption_EncrypTools
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_thinking_a5_encryption_EncrypTools
	 * Method:    doEnDeCryp
	 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_com_thinking_a5_1encryption_EncrypTools_doEnDeCryp
		(JNIEnv *, jclass, jint, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
